esphome:
  name: gm861_uart_example
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  parity: NONE
  stop_bits: 1

external_components:
  - source:
      type: git
      url: https://github.com/mudpoet/esphome-gm861.git
    components: [gm861_uart]

gm861_uart:
  id: gm861_reader
  barcode_sensor:
    name: "GM861 Barcode"
  heartbeat_status:
    name: "GM861 Heartbeat Status"

binary_sensor:
  - platform: template
    name: "GM861 Connection Status"
    lambda: |-
      return id(gm861_reader).is_connected();
    filters:
      - delayed_off: 15s
    on_press:
      then:
        - logger.log: "GM861 connection lost!"

sensor:
  - platform: template
    name: "GM861 Heartbeat Failures"
    lambda: |-
      return id(gm861_reader).get_consecutive_failures();
    accuracy_decimals: 0
    update_interval: 10s

api:
ota:
  - platform: esphome
    password: !secret ota_password
